### ISSUE TITLE
Cannot import metadata in my feature

### ISSUE THREAD

**Issue by leix28** [HDI-Project/ballet-fragile-families#17]
Error message: 

```
families/src/fragile_families/features/contrib/user_leix28/feature_7dc1b617_02ef_4a0d_8101_91788362e464.py", line 3, in <module>
621    import fragile_families.analysis.metadata as metadata
622  File "/home/travis/build/HDI-Project/ballet-fragile-families/src/fragile_families/analysis/metadata.py", line 4, in <module>
623    import ff
624ModuleNotFoundError: No module named 'ff'
625
```

**Comment by micahjsmith** [comment]
Thanks for the question, currently the metadata module (and its dependency `ffmetadata-py` which is imported as `ff`) is meant for feature development only, but is not available normally when the feature engineering pipeline is being used and executed. So far the metadata functionality is [part of the analysis extra](https://github.com/HDI-Project/ballet-fragile-families/blob/master/setup.py#L10) so it is not installed during feature validation.
